name: safe_city_mobile
description: "SEP490 - GSU25SE61 - Safe City Mobile"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.8.1

#Packages
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Utility Packages
  http: ^1.4.0
  http_parser: ^4.1.2
  intl: ^0.20.2
  path: ^1.9.1
  logger: ^2.5.0
  lottie: ^3.3.1
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.4
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  permission_handler: ^12.0.0+1
  vibration: ^3.1.3
  flutter_dotenv: ^5.2.1
  table_calendar: ^3.2.0
  flutter_secure_storage: ^9.2.4
  encrypt: ^5.0.3
  jwt_decoder: ^2.0.1
  camera: ^0.11.1
  flutter_decorated_container: ^1.0.0
  local_auth: ^2.3.0
  shared_preferences: ^2.5.3
  device_info_plus: ^11.5.0
  webview_flutter: ^4.13.0
  app_links: ^6.4.0
  infinite_scroll_pagination: ^5.1.0
  fl_chart: ^1.0.0

  #Maps Integration
  mapbox_maps_flutter: ^2.9.0
  geolocator: ^14.0.2

  #Local Notification
  awesome_notifications: ^0.10.1
  flutter_background_service: ^5.1.0

  # Icons Packages
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  #Specific
  readmore: ^3.0.0
  flutter_quill: ^11.4.2
  flutter_quill_extensions: ^11.0.0

  #Firebase
  #  firebase_core: ^3.5.0
  #  cloud_firestore: ^5.4.2
  #  firebase_auth: ^5.3.0
  #  firebase_storage: ^12.3.2
  #  firebase_messaging: ^15.1.3
  #  firebase_analytics: ^11.3.3
  image_picker: ^1.1.2
  video_player: ^2.10.0
  file_picker: ^10.2.0
  path_provider: ^2.1.5

  #State Management
  get: ^4.7.2
  get_storage: ^2.1.1

  #Google Signin
  google_sign_in: ^6.2.1
  flutter_rating_bar: ^4.0.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0

  #Animations
  animations: ^2.0.11


#Packages end here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/safecity-logo.png"
  adaptive_icon_foreground: "assets/logos/safecity-logo.png"
  adaptive_icon_background: "#000000"

flutter:
  uses-material-design: true

  # Local assets
  assets:
    - .env
    - assets/logos/
    - assets/icons/
    - assets/images/email_verification/
    - assets/images/password_reset/
    - assets/images/loading/
    - assets/images/payments/
    - assets/images/signin/
    - assets/images/ranking/
    - assets/images/default_avatar/
    - assets/images/status/
    - assets/images/map/

  # Local fonts:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.otf
          weight: 300
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-Italic.otf
          style: italic
        - asset: assets/fonts/Inter-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 800
